export const FETCH_OFFICE_REQUEST = "FETCH_OFFICE_REQUEST";
export const FETCH_OFFICE_SUCCESS = "FETCH_OFFICE_SUCCESS";
export const FETCH_OFFICE_FALIURE = "FETCH_OFFICE_FALIURE";
export const POST_OFFICE_REQUEST = "POST_OFFICE_REQUEST";
export const POST_OFFICE_SUCCESS = "POST_OFFICE_SUCCESS";
export const POST_OFFICE_FALIURE = "POST_OFFICE_FALIURE";
